Conda env in /home/mix060514/pj/finmind/.conda activated
pipenv run celery -A financialdata.tasks.worker worker --loglevel=info --concurrency=1 --hostname=%h -Q twse
Loading .env environment variables...
 
 -------------- celery@mix060514-Predator-PH317-53 v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- Linux-6.8.0-49-generic-x86_64-with-glibc2.39 2024-11-30 11:17:52
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         task:0x78822d1d5550
- ** ---------- .> transport:   amqp://worker:**@127.0.0.1:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> twse             exchange=twse(direct) key=twse
                

[tasks]
  . financialdata.tasks.task.crawler

[2024-11-30 11:17:52,798: WARNING/MainProcess] /home/mix060514/.local/share/virtualenvs/finmind-tvQprbtk/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-11-30 11:17:52,799: ERROR/MainProcess] consumer: Cannot connect to amqp://worker:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 2.00 seconds... (1/100)

[2024-11-30 11:17:54,800: ERROR/MainProcess] consumer: Cannot connect to amqp://worker:**@127.0.0.1:5672//: [Errno 104] Connection reset by peer.
Trying again in 4.00 seconds... (2/100)

[2024-11-30 11:17:58,818: INFO/MainProcess] Connected to amqp://worker:**@127.0.0.1:5672//
[2024-11-30 11:17:58,820: WARNING/MainProcess] /home/mix060514/.local/share/virtualenvs/finmind-tvQprbtk/lib/python3.13/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-11-30 11:17:58,828: INFO/MainProcess] mingle: searching for neighbors
[2024-11-30 11:17:59,873: INFO/MainProcess] mingle: all alone
[2024-11-30 11:17:59,913: INFO/MainProcess] celery@mix060514-Predator-PH317-53 ready.
[2024-11-30 11:18:03,651: INFO/MainProcess] Events of group {task} enabled by remote.
